#!/bin/bash

FILES_TO_COPY="Makefile .gitignore"

print_usage() {
	>&2 echo "Usage:"
	>&2 echo "$0 DIRECTORY BINARY_NAME"
	exit 1
}

[[ ! "$#" -eq 2 ]] && print_usage

TARGET_DIR="$1"
BINARY_NAME="$2"

TARGET_DIR="$(realpath "$TARGET_DIR")"

echo "Initializing project into $TARGET_DIR"

# Ask for confirmation if any files will be overwritten
FILES_TO_OVERWRITE=""
for filename in $FILES_TO_COPY; do
	if [[ -e "$TARGET_DIR/$filename" ]]; then
		FILES_TO_OVERWRITE="$FILES_TO_OVERWRITE$filename "
	fi
done
if [[ -n "$FILES_TO_OVERWRITE" ]]; then
	echo "The following files in $TARGET_DIR will be overwritten:"
	echo `tput setaf 1`"$FILES_TO_OVERWRITE"`tput sgr0`
	read -p "Continue (y/n)? " -n 1 -r
	echo
	if [[ ! $REPLY =~ ^[Yy]$ ]]; then
		 exit 1
	fi
fi

# Go to this script's directory, where the files reside
cd $(dirname "$BASH_SOURCE")

mkdir -p "$TARGET_DIR"

cp -f Makefile "$TARGET_DIR/Makefile"
cp -f gitignore "$TARGET_DIR/.gitignore"

sed -i -e "s/BINARYNAME_PLACEHOLDER/$BINARY_NAME/" \
	"$TARGET_DIR/Makefile" "$TARGET_DIR/.gitignore"

mkdir -p "$TARGET_DIR/src"
mkdir -p "$TARGET_DIR/include"

echo "Initialization completed!"
